# Generated by Django 5.1.4 on 2024-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastnem', models.CharField(max_length=755, null=True)),
                ('emailAddress', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=755, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
