# Generated by Django 5.1.4 on 2024-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0005_user_dateofbirth_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
