# Generated by Django 5.1.4 on 2024-12-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0006_remove_user_dateofbirth_remove_user_emailaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
