# Generated by Django 5.1.4 on 2025-01-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0008_violation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='description',
        ),
        migrations.AlterField(
            model_name='violation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
