# Generated by Django 5.1.4 on 2025-01-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0009_remove_violation_description_alter_violation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
