# Generated by Django 5.1.4 on 2025-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0010_alter_violation_penalty_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='violator_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
