# Generated by Django 5.1.4 on 2025-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0011_remove_ticket_violator_name_ticket_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='ticket',
            name='license_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='plate_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
