# Generated by Django 5.1.4 on 2025-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0012_remove_ticket_license_plate_ticket_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fine_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='violation_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
