# Generated by Django 5.1.4 on 2025-01-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0013_ticket_due_date_ticket_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issued_by',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
