# Generated by Django 5.1.4 on 2025-04-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0020_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
