# Generated by Django 5.1.4 on 2025-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsApp', '0021_ticket_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='driver_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
